### ISSUE TITLE
error: TE/FLEX is incorrect position name

### ISSUE THREAD

**Issue by Locc211** [DimaKudosh/pydfs-lineup-optimizer#126]
I'm trying to limit the FLEX position to not include TE's.

I believe I would do it with :optimizer.set_players_with_same_position.

When I set it to optimizer.set_players_with_same_position({r'TE': 1}) nothing changes and every lineup has a TE in the FLEX position.

When I set it to optimizer.set_players_with_same_position({r'TE/FLEX': 1})

I get the following error:

Traceback (most recent call last):
  File "optimizer6.py", line 3, in <module>
    optimizer.set_players_with_same_position({r'TE/FLEX': 1})
  File "**FILE**", line 325, in set_players_with_same_position
    self._check_position_constraint(pos)
  File "**FILE**", line 557, in _check_position_constraint
    raise LineupOptimizerIncorrectPositionName('%s is incorrect position name.' % position)
pydfs_lineup_optimizer.exceptions.LineupOptimizerIncorrectPositionName: TE/FLEX is incorrect position name.

(**FILE** replaces my actual path).

Am I doing something incorrect?

**Comment by Locc211** [comment]
I found a related question:

https://github.com/DimaKudosh/pydfs-lineup-optimizer/issues/28

If I set the TE:0 then I get a better mix of players in the FLEX position but I still have TE's.

If I set it to WR:1 or RB:1 then I only get those players as FLEX position. 

I can work with this to eliminate TE's from the FLEX position.
