### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by brente33** [DimaKudosh/pydfs-lineup-optimizer#175]
I was making lineups tonight and noticed the update. I pulled in the changes and now all I get is this, even when I just try to check the version. I would appreciate any help!

Traceback (most recent call last):
  File "C:/Users/brent/PycharmProjects/pydfs-lineup-optimizer/FD Cash.py", line 1, in <module>
    from pydfs_lineup_optimizer import Site, Sport, get_optimizer, CSVLineupExporter
  File "C:\Users\brent\PycharmProjects\pydfs-lineup-optimizer\pydfs_lineup_optimizer\__init__.py", line 6, in <module>
    from pydfs_lineup_optimizer.lineup_optimizer import LineupOptimizer
  File "C:\Users\brent\PycharmProjects\pydfs-lineup-optimizer\pydfs_lineup_optimizer\lineup_optimizer.py", line 7, in <module>
    from pydfs_lineup_optimizer.solvers import Solver, PuLPSolver, SolverException
  File "C:\Users\brent\PycharmProjects\pydfs-lineup-optimizer\pydfs_lineup_optimizer\solvers\__init__.py", line 1, in <module>
    from pydfs_lineup_optimizer.solvers.pulp_solver import Solver, PuLPSolver
  File "C:\Users\brent\PycharmProjects\pydfs-lineup-optimizer\pydfs_lineup_optimizer\solvers\pulp_solver.py", line 7, in <module>
    class PuLPSolver(Solver):
  File "C:\Users\brent\PycharmProjects\pydfs-lineup-optimizer\pydfs_lineup_optimizer\solvers\pulp_solver.py", line 8, in PuLPSolver
    LP_SOLVER = PULP_CBC_CMD(verbose=False, msg=False)
  File "C:\Users\brent\PycharmProjects\pydfs-lineup-optimizer\venv\lib\site-packages\pulp\solvers.py", line 1608, in __init__
    COIN_CMD.__init__(self, path=self.pulp_cbc_path, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'verbose'

**Comment by brente33** [comment]
Nevermind. Had to update Pulp even though the requirements says the old version.

**Comment by bimpyinu** [comment]
Did you do anything other than pip install pulp --upgrade? It seems like my pulp version is up to date but I still get the same issue that you had
