### ISSUE TITLE
salary range constraint 

### ISSUE THREAD

**Issue by Denwen12** [DimaKudosh/pydfs-lineup-optimizer#238]
any way i can convert this into a salary range constraint @DimaKudosh 

for player in optimizer.players: 
    if 'C' in player.positions: 

add player salary range between 5000 - 8000

**Comment by Denwen12** [comment]
i tryed
import pandas as pd
csv_filepath = '/root/NBA/2Slate/players-list.csv'
cdf = pd.read_csv(csv_filepath)

#set this to whatever you want the correlation cutoff to be
min_correlation_threshold = 4000
max_correlation_threshold = 8000

```
for player in optimizer.players: 
	if 'C' in player.positions:
                for i in range(len(cdf)):
                    if cdf['Salary'].iloc[i] <= min_correlation_threshold:
                       players = (cdf['Nickname'].iloc[i])
                       group = PlayersGroup([optimizer.get_player_by_name(name) for name in (players)])
                       optimizer.add_players_group(group)
```

But this doesnt work plus cant figure out how to get min and max to work

**Comment by Denwen12** [comment]
Anyone have an idea how this can be done ? @sansbacon

**Comment by sansbacon** [comment]
If you are trying to exclude players based on salary and position, I'd do that in my player pool before I even run the optimizer. What are you trying to accomplish with this rule?

**Comment by Denwen12** [comment]
i know that can work but id like to know if there is a way to do it with
code

**Comment by Denwen12** [comment]
i am testing something but do you know a code way i can use?

**Comment by sansbacon** [comment]
So, who is supposed to be in the PlayersGroup? The way your code works right now it looks like you are only adding one player to the player group (whatever name is found at ```cdf['Nickname'].iloc[i]```). It also looks like the original player from ```optimizer.players``` is not added to the group.

I'm still not sure exactly what you are trying to do, so I'm going to have to guess and you can adapt the code accordingly. Assume I want to pair any player with C eligibility with a player whose salary is <= ```min_price```.

```
# find all of the players you want to pair
# you can add more conditions to the list comprehension if needed
centers = [p for p in optimizer.players if 'C' in player.positions]

for c in centers:
    # it is bad practice to loop over pandas dataframes with integer indexes
    # you should either use vectorized operations or itertuples/iterrows
    # here, you can use loc to find the group of players that meet your criteria
    # make sure to exclude the center's name from the results
    cheap_player_names = cdf.loc[(cdf['Salary'] <= min_price) & (cdf['Nickname'] != c.full_name), 'Nickname']
    
    # combine the center and the list of cheap players
    players_to_group = [c] + [optimizer.get_player_by_name(name) for name in cheap_player_names]

    # create the players group, I think you want to set some of the optional parameters
    group = PlayersGroup(
        players=players_to_group, 
        min_from_group=2,
        max_from_group=???,
        max_exposure=????
    )

    # add the PlayersGroup to the optimizer
    optimizer.add_players_group(group)
```

**Comment by Denwen12** [comment]
sorry if i confused you. what i want is to create a group in the min and
max price range for centers

**Comment by sansbacon** [comment]
If that is what you are trying to do, why do you need the dataframe? Isn't all of the information you need in the Player objects? There is no need to call ```find_player_by_name``` if you already have the Player object, as you can just add those objects to the PlayersGroup directly.

```
centers = [p for p in optimizer.players if 'C' in player.positions and p.salary >= min_price and p.salary <= max_price]
group = PlayersGroup(
  players=centers, 
  min_from_group=???,
  max_from_group=???,
  max_exposure=????
)
optimizer.add_players_group(group)
```

**Comment by Denwen12** [comment]
I am still learning python on my own so i was limited 🤣🤣🤣

**Comment by Denwen12** [comment]
so what i am doing is i renamed the positions to pg1, pg 2 now iam going to set ranges for each position

**Comment by Denwen12** [comment]
i created a database about winning lineups on salary and slate sizes

**Comment by Denwen12** [comment]
and thank you, I will try this out soon

**Comment by Denwen12** [comment]
i got this @sansbacon 

max_price]
  File "Fanduel2Finish.py", line 92, in <listcomp>
    centers = [p for p in optimizer.players if 'C' in player.positions and p.salary >= min_price and p.salary <= max_price]
NameError: name 'player' is not defined

**Comment by Denwen12** [comment]
I fixed it

**Comment by Denwen12** [comment]
Thank you so much. This works fantastic

**Comment by Denwen12** [comment]
Hello @sansbacon 
Thanks for helping me with this, so now i got a new question i have a csv with ownership column and player names column that is separate and how can i incorporate this and have it select players within the numbers maybe players inbetween 10 and 25

```
sg_max_price = 11000
sg_min_price = 5000
SG = [player for player in optimizer.players if 'SG' in player.positions and player.salary >= sg_min_price and player.salary <= sg_max_price]
SG = PlayersGroup(players=SG, min_from_group=1 )
optimizer.add_players_group(SG)
```

**Comment by Denwen12** [comment]
here is a sample of my csv


Name | Salary | Position | Matchup | Team | Opponent | Ownership %
-- | -- | -- | -- | -- | -- | --
Damian Lillard | 9700 | PG | POR@CHI | POR | CHI | 34.2
DeMar DeRozan | 7300 | SG | MEM@SA | SA | MEM | 29
LaMelo Ball | 5200 | PG | MIL@CHA | CHA | MIL | 27.7
Giannis Antetokounmpo | 11300 | PF | MIL@CHA | MIL | CHA | 26.7
Tyrese Haliburton | 4900 | SG | SAC@MIA | SAC | MIA | 26.5
Steven Adams | 5200 | C | HOU@NO | NO | HOU | 25.7
Gordon Hayward | 7200 | SF | MIL@CHA | CHA | MIL | 24.7
Chris Paul | 7200 | PG | PHO@DAL | PHO | DAL | 23.9
Zach LaVine | 9000 | SG | POR@CHI | CHI | POR | 23.7
Jerami Grant | 7800 | SF | DET@GS | DET | GS | 21.7
Luka Doncic | 11000 | PG | PHO@DAL | DAL | PHO | 21.6
Brandon Clarke | 6500 | PF | MEM@SA | MEM | SA | 20.5
Enes Kanter | 6900 | C | POR@CHI | POR | CHI | 19.9
Dillon Brooks | 5200 | SG | MEM@SA | MEM | SA | 19.7
Xavier Tillman | 4600 | PF | MEM@SA | MEM | SA | 19.4
Draymond Green | 4900 | PF | DET@GS | GS | DET | 18.9
Cameron Johnson | 4600 | SF | PHO@DAL | PHO | DAL | 18.7
Khris Middleton | 8200 | SF | MIL@CHA | MIL | CHA | 17.5
Robert Covington | 4700 | PF | POR@CHI | POR | CHI | 17

**Comment by Denwen12** [comment]
Im not Sure how i can use current projected ownership. I do have the numbers inserted in the
players-list but not sure how i can add that with my setup @sansbacon

**Comment by sansbacon** [comment]
When you create a Player object, there is a parameter for ```projected_ownership```. So if you populate that value when you create the Player object, you can filter on it when you iterate through the Player objects that you loaded into the optimizer.

**Comment by Denwen12** [comment]
can you show me how you would add that into the current code you helped with ..

**Comment by Denwen12** [comment]
i want min 10 to max 25 projected ownership

**Comment by Denwen12** [comment]
also can you show me another way to read the data in the csv as a custom pandas way or whatever way

**Comment by Denwen12** [comment]
When i tryed this for an example i got 

```
sg_max_price = 25
sg_min_price = 14
SG = [player for player in optimizer.players if 'SG' in player.positions and player.projected_ownership >= sg_min_price and player.projected_ownership <= sg_max_price]
SG1 = PlayersGroup(players=SG, min_from_group=1 )
optimizer.add_players_group(SG1)
```


Traceback (most recent call last):
  File "Fanduel2Finish.py", line 112, in <module>
    projected_ownership
NameError: name 'projected_ownership' is not defined

**Comment by Denwen12** [comment]
i Actually got it working by convert to decimal   like 14 
to  .140

**Comment by Denwen12** [comment]
@sansbacon 
it works if i only  use salary or ownership alone but when i try with ownership and salary constraints it cant generate,  i am using 

```
sg_max_projected_ownership = .200
sg_min_projected_ownership = .140
sg_max_price = 15000
sg_min_price = 6900
SG = [player for player in optimizer.players if 'SG' in player.positions and player.salary >= sg_min_price and player.salary <= sg_max_price and player.projected_ownership >= sg_min_projected_ownership and player.projected_ownership <= sg_max_projected_ownership]
SG1 = PlayersGroup(players=SG, min_from_group=1 )
optimizer.add_players_group(SG1)
```

**Comment by Denwen12** [comment]
do you know if there is a way @sansbacon
