### ISSUE TITLE
Restrict Positions for opposing team.

### ISSUE THREAD

**Issue by chrisbach1** [DimaKudosh/pydfs-lineup-optimizer#423]
Anyone know why this wouldnt be working?

optimizer.restrict_positions_for_opposing_team(['P'], ['C', 'SS', 'OF', '1B', '2B', '3B'])

Traceback (most recent call last):
  File "C:\Users\chris\Desktop\MLB\02. MLB Optimizer.py", line 17, in <module>
    optimizer.restrict_positions_for_opposing_team(['P'], ['C', 'SS', 'OF', '1B', '2B', '3B'])
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 350, in restrict_positions_for_opposing_team
    raise ValueError("Each restriction should be a tuple of (first_team_positions, second_team_positions, max_allowed)")
ValueError: Each restriction should be a tuple of (first_team_positions, second_team_positions, max_allowed)
[Finished in 157ms]

**Comment by Milkman9691** [comment]
> Anyone know why this wouldnt be working?
> 
> optimizer.restrict_positions_for_opposing_team(['P'], ['C', 'SS', 'OF', '1B', '2B', '3B'])
> 
> Traceback (most recent call last): File "C:\Users\chris\Desktop\MLB\02. MLB Optimizer.py", line 17, in optimizer.restrict_positions_for_opposing_team(['P'], ['C', 'SS', 'OF', '1B', '2B', '3B']) File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\pydfs_lineup_optimizer\lineup_optimizer.py", line 350, in restrict_positions_for_opposing_team raise ValueError("Each restriction should be a tuple of (first_team_positions, second_team_positions, max_allowed)") ValueError: Each restriction should be a tuple of (first_team_positions, second_team_positions, max_allowed) [Finished in 157ms]

For DK it has to be as follows

optimizer.restrict_positions_for_opposing_team(['SP', 'RP'], ['1B', '1B/2B', '1B/3B', '1B/OF','1B/C','1B/SS', '2B', '2B/C', '2B/3B', '2B/OF', '2B/SS', '3B', '3B/OF', '3B/SS', 'C', 'C/1B', 'C/2B', 'C/OF', 'OF', 'SS','OF/SS', 'SS/OF'])

Not sure position assignments for FD

**Comment by chrisbach1** [comment]
Thank you for the help! @Milkman9691
